version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
      - ./backend/sqlite_data:/usr/src/app/sqlite_data
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

